# Generated by Django 2.2.6 on 2019-10-28 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='votingevent',
            name='event_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='votingevent',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
